FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster as build
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install -g dotnet-ef

WORKDIR /src
COPY token.txt .
COPY SharedVolume SharedVolume
COPY TU20Bot TU20Bot
COPY BotTest BotTest
COPY TU20Bot.sln .

WORKDIR /src
COPY setup.sh .